name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta diariamente a medianoche
  workflow_dispatch: # Permite ejecución manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate Snake Animation
      uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: dist/snake.svg

    - name: Push Snake to Repository
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
